---
# tasks file for rails_app


- include_tasks: rbenv-ruby.yml
- include_tasks: dependencies.yml
- include_tasks: passenger-config.yml
  when: is_webserver
- include_tasks: install-app.yml
- include_tasks: manage-configuration.yml
