---
# tasks file for rails_app

- name: Include rbenv and ruby tasks
  ansible.builtin.include_tasks: rbenv-ruby.yml
- name: Include ependencies tasks
  ansible.builtin.include_tasks: dependencies.yml
- name: Include passenger config tasks
  ansible.builtin.include_tasks: passenger-config.yml
  when: rails_app_is_webserver
- name: Include install app tasks
  ansible.builtin.include_tasks: install-app.yml
- name: Include manage configuration tasks
  ansible.builtin.include_tasks: manage-configuration.yml
