---
# tasks file for rails_app


- include_tasks: dependencies.yml
- include_tasks: passenger-config.yml
  when: is_webserver
- include_tasks: install-app.yml
- include_tasks: manage_configuration.yml
