---
version: 2.1
jobs:
  build:
    working_directory: ~/ansible-rails_app
    docker:
      - image: cimg/python:3.12.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:XXg1PTcrj2uSJLVW+HkXJ5+ARo30Uoo+kNFq9Ik6imk"
      - run:
          name: Install
          command: pipenv install --dev
      - setup_remote_docker
      - run:
          name: Molecule
          command: pipenv run molecule test
