---

- name: Converge
  hosts: all
  vars:
    nodejs_major_version: 23
    nodejs_version: 23.8.0
    rails_app_name: test_app
    rails_app_user: test_app
    ruby_version: 3.4.1
    ruby_abi_version: "{{ ruby_version | regex_replace('^(\\d+\\.\\d+)\\.\\d+$', '\\1.0') }}"
    bundler_version: 2.6.2
    rbenv_user_profile: true
    rails_app_use_webpack: true
    rails_app_git_url: https://github.com/tulibraries/rails-nihilist
    rails_app_git_branch: main
    rails_app_prod_secret: EXTREMELY_LONG_SECRET_VALUE
    rails_app_bundler_configs:
      - key: "NEEDS_FLAGS"
        value: "--with-flags"
    set_pig: true
    rails_app_user_envvars:
      - {envvar: "MOO", value: "cow"}
      - {envvar: "COW", value: "moo", when: "{{ set_cow is defined and set_cow }}"}
      - {envvar: "PIG", value: "oink", when: "{{ set_pig is defined and set_pig }}"}

    httpd_status_enable: true
    mpm_module: event

  pre_tasks:
    - name: Ensure rails app user is present.
      user:
        name: "{{ rails_app_user }}"
        state: present
    - name: Remove conflicting curl-minimal package
      become: true
      dnf:
        name: curl-minimal
        state: absent
      when: ansible_os_family == "RedHat"
    - name: Enable CRB repository
      ansible.builtin.command: dnf config-manager --set-enabled crb
      become: true
      changed_when: false
  roles:
  - role: tulibraries.ansible_role_passenger_apache
  - role: ansible-rails_app
    