---

- name: Prepare
  hosts: all
  vars:
    rails_app_user: nothing
  pre_tasks:
    - name: Add software collections
      yum:
        name:
          - centos-release-scl-rh
        state: present
    - name: install library dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git-core
        - zlib
        - zlib-devel
        - gcc-c++
        - patch
        - readline
        - readline-devel
        - libyaml-devel
        - libffi-devel
        - openssl-devel
        - make
        - bzip2
        - autoconf
        - automake
        - libtool
        - bison
        - curl
        - sqlite-devel
        - httpd
    - name: Ensure rails app user is present.
      user:
        name: "{{ rails_app_user }}"
        state: present

  roles:
    - role: zzet.rbenv
      vars:
        rbenv_users: "{{ rails_app_user }}"
        rbenv_owner: "{{ rails_app_user }}"
        rbenv_group: "{{ rails_app_user }}"
        rbenv_plugins:
          - { name: "rbenv-vars", repo: "https://github.com/rbenv/rbenv-vars.git", version: "master" }
          - { name: "ruby-build", repo: "https://github.com/rbenv/ruby-build.git", version: "master" }
          - { name: "rbenv-default-gems", repo: "https://github.com/rbenv/rbenv-default-gems.git", version: "master" }
          - { name: "rbenv-installer", repo: "https://github.com/rbenv/rbenv-installer.git", version: "main" }
          - { name: "rbenv-update", repo: "https://github.com/rkh/rbenv-update.git", version: "master" }
          - { name: "rbenv-whatis", repo: "https://github.com/rkh/rbenv-whatis.git", version: "master" }
          - { name: "rbenv-use", repo: "https://github.com/rkh/rbenv-use.git", version: "master" }
        rbenv:
          env: user
          version: v1.1.1
          default_ruby: 2.7.2
          rubies:
            - version: 2.7.2

    - role: tulibraries.ansible_role_passenger_apache
