name: Molecule Test

# Temporary variable until molecule-docker officially supports ansible 2.19+
env:
  ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "True"

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  molecule:
    runs-on: [ self-hosted, systemd-runner ]
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [ 3.12 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: kishaningithub/setup-python-amazon-linux@v1
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pipenv"

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install dependencies
        run: pipenv install --dev

      - name: Lint the role
        run: pipenv run ansible-lint . --exclude=molecule/default/roles

      - name: Molecule test
        run: pipenv run molecule test
